[package]
name = "fft"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-bls12-381 = { workspace = true }
field = { path = "../field" }
